/*
 * clase PanelMultiplicarMatrices la cual sera la vista principal de esta seccion en la cual
 * podran realizar operaciones tales como: multiplicar un Matriz A por una Matriz B
 */
package view;

import controller.ControllerMultiplicarMatrices;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author SOFTWARE GALAXIA
 */
public class PanelMultiplicarMatrices extends javax.swing.JPanel {
 
    //Creamos el objeto de nuestra clase controlador
    ControllerMultiplicarMatrices controller;
    
    /*Creamos tres arreglos bidimensionales de tipo JTextField los cuales haran referencia
    a las matrices que trabajaremos */    
    public JTextField [][] JmatrizA, JmatrizB, JmatrizC; 
    public JSeparator separator;
    
    
    public PanelMultiplicarMatrices() {
        
        initComponents();
        
        
        panelAreaResultado.setVisible(false);
        
        separator = new JSeparator();
        
        /*Instanciamos la clase controladora y pasamos como parametros nuestra vista*/
        controller = new ControllerMultiplicarMatrices(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbTitle = new javax.swing.JLabel();
        lbInfo2 = new javax.swing.JLabel();
        lbNumFilasMA = new javax.swing.JLabel();
        lbNumColumnasMA = new javax.swing.JLabel();
        lbNumFilasMB = new javax.swing.JLabel();
        lbNumColumnasMB = new javax.swing.JLabel();
        JcDimensionFilaMatrizA = new javax.swing.JComboBox<>();
        JcDimensionColumnaMatrizA = new javax.swing.JComboBox<>();
        JcDimensionFilaMatrizB = new javax.swing.JComboBox<>();
        JcDimensionColumnaMatrizB = new javax.swing.JComboBox<>();
        btnGenerarMatriz = new javax.swing.JButton();
        panelAreaOperaciones = new javax.swing.JPanel();
        lbInicioIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelAreaResultado = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lbTitle.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbTitle.setText("Multiplicación De Matrices");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(lbTitle, gridBagConstraints);

        lbInfo2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbInfo2.setText("<html><body><p>Seleccione el <b>tamaño</b> de las<b> matrices :</b></p></body></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 10, 10);
        add(lbInfo2, gridBagConstraints);

        lbNumFilasMA.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lbNumFilasMA.setText("<html><body><p>Número de <b>filas</b> de la<b> Matriz A:</b></p> </body> </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 10);
        add(lbNumFilasMA, gridBagConstraints);

        lbNumColumnasMA.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lbNumColumnasMA.setText("<html><body><p>Número de<b> columnas</b> de la<b> Matriz A:</b></p> </body> </html> ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 10);
        add(lbNumColumnasMA, gridBagConstraints);

        lbNumFilasMB.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lbNumFilasMB.setText("<html><body><p>Número de <b>filas</b> de la<b> Matriz B:</b></p> </body> </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 10);
        add(lbNumFilasMB, gridBagConstraints);

        lbNumColumnasMB.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        lbNumColumnasMB.setText("<html><body><p>Número de <b>columnas</b> de la<b> Matriz B:</b></p> </body> </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 10);
        add(lbNumColumnasMB, gridBagConstraints);

        JcDimensionFilaMatrizA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));
        JcDimensionFilaMatrizA.setPreferredSize(new java.awt.Dimension(31, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        add(JcDimensionFilaMatrizA, gridBagConstraints);

        JcDimensionColumnaMatrizA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));
        JcDimensionColumnaMatrizA.setPreferredSize(new java.awt.Dimension(31, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        add(JcDimensionColumnaMatrizA, gridBagConstraints);

        JcDimensionFilaMatrizB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));
        JcDimensionFilaMatrizB.setPreferredSize(new java.awt.Dimension(31, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        add(JcDimensionFilaMatrizB, gridBagConstraints);

        JcDimensionColumnaMatrizB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));
        JcDimensionColumnaMatrizB.setPreferredSize(new java.awt.Dimension(31, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        add(JcDimensionColumnaMatrizB, gridBagConstraints);

        btnGenerarMatriz.setBackground(new java.awt.Color(117, 214, 255));
        btnGenerarMatriz.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGenerarMatriz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate.png"))); // NOI18N
        btnGenerarMatriz.setText(" Generar");
        btnGenerarMatriz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarMatriz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerarMatriz.setOpaque(false);
        btnGenerarMatriz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 20);
        add(btnGenerarMatriz, gridBagConstraints);

        panelAreaOperaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos De Entrada", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        panelAreaOperaciones.setOpaque(false);
        panelAreaOperaciones.setLayout(new java.awt.GridBagLayout());

        lbInicioIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/algebra-lineal.png"))); // NOI18N
        panelAreaOperaciones.add(lbInicioIcon, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(panelAreaOperaciones, gridBagConstraints);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnCalcular.setBackground(new java.awt.Color(255, 83, 83));
        btnCalcular.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calcular-suma.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.setIconTextGap(14);
        btnCalcular.setPreferredSize(new java.awt.Dimension(227, 67));
        jPanel1.add(btnCalcular);

        btnLimpiar.setBackground(new java.awt.Color(123, 167, 225));
        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clean.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(227, 67));
        jPanel1.add(btnLimpiar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        add(jPanel1, gridBagConstraints);

        panelAreaResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        panelAreaResultado.setOpaque(false);
        panelAreaResultado.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        add(panelAreaResultado, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> JcDimensionColumnaMatrizA;
    public javax.swing.JComboBox<String> JcDimensionColumnaMatrizB;
    public javax.swing.JComboBox<String> JcDimensionFilaMatrizA;
    public javax.swing.JComboBox<String> JcDimensionFilaMatrizB;
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnGenerarMatriz;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbInfo2;
    public javax.swing.JLabel lbInicioIcon;
    private javax.swing.JLabel lbNumColumnasMA;
    private javax.swing.JLabel lbNumColumnasMB;
    private javax.swing.JLabel lbNumFilasMA;
    private javax.swing.JLabel lbNumFilasMB;
    private javax.swing.JLabel lbTitle;
    public javax.swing.JPanel panelAreaOperaciones;
    public javax.swing.JPanel panelAreaResultado;
    // End of variables declaration//GEN-END:variables
}
