/*
 * Vista PanelSumarMatrices, interfaz grafica en la cual el usuario podra hacer operaciones
 * para calcular la suma entre una matriz A y B.
 */
package view;

import controller.ControllerSumarMatrices;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author SOFTWARE GALAXIA TV
 */
public class PanelSumarMatrices extends javax.swing.JPanel {

    // llamamos nuestro objeto controlador
    ControllerSumarMatrices controller;
    
    /*Creamos tres arreglos bidimensionales de tipo JTextField los cuales haran referencia
    a las matrices que trabajaremos */    
    public JTextField [][] JmatrizA, JmatrizB, JmatrizC; 
    public JSeparator separator;

    
    
    public PanelSumarMatrices() {
        initComponents();
        
        panelAreaResultado.setVisible(false);
        
        /*Asignamos dimensiones a los arreglos */
        JmatrizA = new JTextField[2][2];
        JmatrizB= new JTextField[2][2];        
        JmatrizC = new JTextField[2][2]; 
        
        separator = new JSeparator();
        
        
        //instanciamos la clase de nuestro objeto controlador y le pasamos como parametro la vista
        // de esta manera conectamos la vista de nuestra aplicacion con su respectivo controlador
        controller = new ControllerSumarMatrices(this);
        
    }

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelTitle = new javax.swing.JLabel();
        JcDimensionFila = new javax.swing.JComboBox<>();
        labelFormula = new javax.swing.JLabel();
        labelDimensionFila = new javax.swing.JLabel();
        panelAreaOperaciones = new javax.swing.JPanel();
        labelDimensionColumna = new javax.swing.JLabel();
        JcDimensionColumna = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelAreaResultado = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        labelTitle.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        labelTitle.setText("Suma De Matrices");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(labelTitle, gridBagConstraints);

        JcDimensionFila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));
        JcDimensionFila.setPreferredSize(new java.awt.Dimension(31, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(JcDimensionFila, gridBagConstraints);

        labelFormula.setBackground(new java.awt.Color(171, 178, 185));
        labelFormula.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelFormula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFormula.setText("Matriz C = A + B");
        labelFormula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelFormula.setPreferredSize(new java.awt.Dimension(175, 39));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(labelFormula, gridBagConstraints);

        labelDimensionFila.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelDimensionFila.setText("Numero De Filas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 10);
        add(labelDimensionFila, gridBagConstraints);

        panelAreaOperaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Entrada", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        panelAreaOperaciones.setOpaque(false);
        panelAreaOperaciones.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(panelAreaOperaciones, gridBagConstraints);

        labelDimensionColumna.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelDimensionColumna.setText("Número De Columnas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        add(labelDimensionColumna, gridBagConstraints);

        JcDimensionColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));
        JcDimensionColumna.setPreferredSize(new java.awt.Dimension(31, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        add(JcDimensionColumna, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        btnCalcular.setBackground(new java.awt.Color(255, 83, 83));
        btnCalcular.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calcular-suma.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCalcular.setIconTextGap(14);
        btnCalcular.setMaximumSize(new java.awt.Dimension(167, 47));
        btnCalcular.setPreferredSize(new java.awt.Dimension(227, 67));
        jPanel1.add(btnCalcular);

        btnLimpiar.setBackground(new java.awt.Color(123, 167, 225));
        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clean.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpiar.setIconTextGap(14);
        btnLimpiar.setPreferredSize(new java.awt.Dimension(227, 67));
        jPanel1.add(btnLimpiar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        add(jPanel1, gridBagConstraints);

        panelAreaResultado.setBackground(new java.awt.Color(255, 255, 255));
        panelAreaResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        panelAreaResultado.setOpaque(false);
        panelAreaResultado.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(panelAreaResultado, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> JcDimensionColumna;
    public javax.swing.JComboBox<String> JcDimensionFila;
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDimensionColumna;
    private javax.swing.JLabel labelDimensionFila;
    private javax.swing.JLabel labelFormula;
    private javax.swing.JLabel labelTitle;
    public javax.swing.JPanel panelAreaOperaciones;
    public javax.swing.JPanel panelAreaResultado;
    // End of variables declaration//GEN-END:variables
}
